# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Safe2HomeIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Safe2HomeIOS

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FirebaseDatabase'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'GoogleSignIn'




  target 'Safe2HomeIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Safe2HomeIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
